[package]
name = "grpc-account-tracking"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
magicblock-core = { workspace = true }
solana-client = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true }
