[package]
name = "integration-test-tools"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
magicblock-core = { workspace = true }
magicblock-config = { workspace = true }
magicblock-delegation-program = { workspace = true, features = [
  "no-entrypoint",
] }
solana-pubkey = { workspace = true }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
