[package]
name = "integration-test-tools"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
color-backtrace = { workspace = true }
cleanass = { workspace = true }
tracing = { workspace = true }
random-port = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
ureq = { workspace = true }
url = { workspace = true }
magicblock-core = { workspace = true }
magicblock-config = { workspace = true }
magicblock-delegation-program = { workspace = true, features = [
  "no-entrypoint",
] }
program-flexi-counter = { workspace = true, features = ["no-entrypoint"] }
solana-pubkey = { workspace = true }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
