remote = "devnet"
lifecycle = "offline"
commit = { compute-unit-price = 1_000_000 }
listen = "0.0.0.0:7799"

[accountsdb]
database-size = 1048576000
block-size = "block256"
index-size = 2048576
max-snapshots = 7
snapshot-frequency = 1024

[ledger]
reset = true
block-time = "50ms"

[[programs]]
id = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
path = "../schedulecommit/elfs/dlp.so"
