lifecycle = "ephemeral"
remotes = ["http://0.0.0.0:7799", "ws://0.0.0.0:7800"]

[aperture]
listen = "0.0.0.0:8899"

[commit]
compute-unit-price = 1_000_000

[ledger]
reset = true
block-time = "50ms"

[task-scheduler]
reset = true
