remote = "devnet"
lifecycle = "offline"
commit = { compute-unit-price = 1_000_000 }
listen = "0.0.0.0:7799"

[ledger]
block-time = "50ms"

[[programs]]
id = "f1exzKGtdeVX3d6UXZ89cY7twiNJe9S5uq84RTA4Rq4"
path = "../target/deploy/program_flexi_counter.so"

[[programs]]
id = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
path = "../schedulecommit/elfs/dlp.so"

[[programs]]
id = "DmnRGfyyftzacFb1XadYhWF6vWqXwtQk5tbr6XgR3BA1"
path = "../schedulecommit/elfs/mdp.so"

[[programs]]
id = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
path = "../programs/noop/noop.so"

[metrics]
address = "0.0.0.0:9000"
