remote = "devnet"
lifecycle = "offline"
commit = { compute-unit-price = 1_000_000 }
listen = "0.0.0.0:7799"

[accountsdb]
# size of the main storage, we have to preallocate in advance
# it's advised to set this value based on formula 1KB * N * 3,
# where N is the number of accounts expected to be stored in
# database, e.g. for million accounts this would be 3GB
database-size = 1048576000 # 1GB
# minimal indivisible unit of addressing in main storage
# offsets are calculated in terms of blocks
block-size = "block256" # possible values block128 | block256 | block512
# size of index file, we have to preallocate,
# can be as low as 1% of main storage size, but setting it to higher values won't hurt
index-size = 2048576
# max number of snapshots to keep around
max-snapshots = 7
# how frequently (slot-wise) we should take snapshots
snapshot-frequency = 1024
reset = true

[ledger]
reset = true
block-time = "50ms"

[[programs]]
id = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
path = "../schedulecommit/elfs/dlp.so"

[[programs]]
id = "DmnRGfyyftzacFb1XadYhWF6vWqXwtQk5tbr6XgR3BA1"
path = "../schedulecommit/elfs/mdp.so"

# NOTE: `cargo build-sbf` needs to run from the root to build the program
[[programs]]
id = "ComtrB2KEaWgXsW1dhr1xYL4Ht4Bjj3gXnnL6KMdABq"
path = "../../target/deploy/magicblock_committor_program.so"

[[programs]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "../target/deploy/program_schedulecommit.so"

[[programs]]
id = "4RaQH3CUBMSMQsSHPVaww2ifeNEEuaDZjF9CUdFwr3xr"
path = "../target/deploy/program_schedulecommit_security.so"

[metrics]
address = "0.0.0.0:9000"
