[package]
name = "genx"
version = "0.0.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
base64 = { workspace = true }
clap = { version = "4.5.23", features = ["derive"] }
magicblock-accounts-db = { workspace = true, features = [ "dev-tools" ] }
json = { workspace = true }
solana-rpc-client = { workspace = true }
solana-commitment-config = { workspace = true }
solana-pubkey = { workspace = true }
tempfile = { workspace = true }
