[package]
name = "magicblock-task-scheduler"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
magicblock-core = { workspace = true }
magicblock-config = { workspace = true }
magicblock-ledger = { workspace = true }
magicblock-program = { workspace = true }
rusqlite = { workspace = true }
solana-timings = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
solana-program = { workspace = true }
solana-pubsub-client = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["time"] }

[dev-dependencies]
magicblock-magic-program-api = { workspace = true }
test-kit = { workspace = true }
guinea = { workspace = true }
solana-account = { workspace = true }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
