blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/magicblock-labs/magicblock-validator/discussions
    about: Q&A / ideas
  - name: Security
    url: https://github.com/magicblock-labs/magicblock-validator/security/policy
    about: Report privately
