[package]
name = "ledger-stats"
version = "0.0.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
magicblock-accounts-db = { workspace = true }
magicblock-core = { workspace = true }
magicblock-ledger = { workspace = true }
num-format = { workspace = true }
pretty-hex = "0.4.1"
solana-account = { workspace = true }
solana-clock = { workspace = true }
solana-message = { workspace = true }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
solana-transaction-status = { workspace = true }
structopt = "0.3"
tabular = "0.2"
