[package]
name = "magicblock-validator-admin"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
# magicblock-accounts = { workspace = true }

magicblock-config = { workspace = true }
magicblock-delegation-program = { workspace = true }
magicblock-mutator = { workspace = true }
magicblock-program = { workspace = true }
magicblock-rpc-client = { workspace = true }


solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
