[package]
name = "magicblock-validator-admin"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }

magicblock-delegation-program = { workspace = true }
magicblock-program = { workspace = true }
magicblock-rpc-client = { workspace = true }


solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
