[package]
name = "magicblock-magic-program-api"
description = "Magicblock magic program api"
license = "MIT"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
solana-program = ">0"
bincode = ">0"
serde = ">0"
