[package]
name = "magicblock-magic-program-api"
description = "Magicblock magic program api"
license = "MIT"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
solana-program = ">=1.16, <3.0.0"
bincode = { version = "2.0.1", default-features = false, features = ["alloc", "serde"] }
serde = { version = "^1.0.228", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
bincode1 = { package = "bincode", version = "1.3.3" }
