[package]
name = "magicblock-validator"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
default-run = "magicblock-validator"

[dependencies]
console-subscriber = { workspace = true, optional = true }
env_logger = { workspace = true }
log = { workspace = true }
magicblock-api = { workspace = true }
magicblock-config = { workspace = true }
magicblock-version = { workspace = true }
num_cpus = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[features]
default = []
tokio-console = ["console-subscriber", "tokio/tracing"]
