[package]
name = "magicblock-validator"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
default-run = "magicblock-validator"

[dependencies]
console-subscriber = { workspace = true, optional = true }
magicblock-api = { workspace = true }
magicblock-core = { workspace = true }
magicblock-config = { workspace = true }
magicblock-tui = { workspace = true, optional = true }
magicblock-version = { workspace = true }
num_cpus = { workspace = true }
solana-signer = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }

[features]
default = []
tokio-console = ["console-subscriber", "tokio/tracing"]
tui = ["magicblock-tui", "magicblock-api/tui"]
