[workspace]
members = ["grpc-account-tracking", "grpc-undelegation-tracking"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
borsh = "1.5"
env_logger = "0.11"
futures = "0.3"
helius-laserstream = { git = "https://github.com/magicblock-labs/laserstream-sdk", branch = "v0.2.2-magicblock" }
magicblock-core = { path = "../magicblock-core" }
magicblock-delegation-program = { git = "https://github.com/magicblock-labs/delegation-program.git", rev = "1874b4f5f5f55cb9ab54b64de2cc0d41107d1435", features = [
  "no-entrypoint",
] }
reqwest = "0.11"
solana-client = "2.2"
solana-rpc-client = "2.2"
solana-sdk = "2.2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
yellowstone-grpc-proto = "7.0.0"

[[workspace.bin]]
name = "grpc-account-tracking"
path = "grpc-account-tracking/src/main.rs"

[[workspace.bin]]
name = "grpc-undelegation-tracking"
path = "grpc-undelegation-tracking/src/main.rs"

[patch.crates-io]
solana-account = { git = "https://github.com/magicblock-labs/solana-account.git", rev = "2246929" }
