[package]
name = "schedulecommit-committor-service"
version.workspace = true
edition.workspace = true

[dev-dependencies]
async-trait = { workspace = true }
borsh = { workspace = true }
compressed-delegation-client = { workspace = true }
light-client = { workspace = true, features = ["v2"] }
light-compressed-account = { workspace = true }
light-sdk = { workspace = true, features = ["v2"] }
light-sdk-types = { workspace = true, features = ["v2"] }
log = { workspace = true }
futures = { workspace = true }
magicblock-chainlink = { workspace = true }
magicblock-committor-program = { workspace = true, features = [
  "no-entrypoint",
] }
magicblock-committor-service = { workspace = true, features = [
  "dev-context-only-utils",
] }
magicblock-core = { workspace = true }
magicblock-delegation-program = { workspace = true, features = [
  "no-entrypoint",
] }
magicblock-program = { workspace = true }
magicblock-rpc-client = { workspace = true }
magicblock-table-mania = { workspace = true, features = [
  "randomize_lookup_table_slot",
] }
program-flexi-counter = { workspace = true, features = ["no-entrypoint"] }
rand = { workspace = true }
solana-account = { workspace = true }
solana-pubkey = { workspace = true }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sdk = { workspace = true }
test-kit = { workspace = true }
tokio = { workspace = true }

[features]
test_table_close = []
